"""Generate browser constants from the frozen V3 JSON artifact."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path


def main():
    root = Path(__file__).resolve().parents[1]
    source = root / "data/processed/face_shape_v3_mlp_model.json"
    target = root / "frontend/js/vision/face-classifier-v3-model.generated.js"
    source_bytes = source.read_bytes()
    model = json.loads(source_bytes)
    digest = hashlib.sha256(source_bytes).hexdigest()
    payload = json.dumps(model, separators=(",", ":"), ensure_ascii=True)
    content = (
        "// Generated by tools/generate_face_classifier_v3_browser_model.py. Do not edit.\n"
        f"// Source SHA-256: {digest}\n"
        f"export const FACE_CLASSIFIER_V3_MODEL = Object.freeze({payload});\n"
    )
    target.write_text(content, encoding="ascii", newline="\n")
    print(target)


if __name__ == "__main__":
    main()
